#!/bin/bash

function cerf {
  if [[ -f "$1" ]]; then
    echo "Refusing to overwrite your $1 file."
    exit 1
  fi
}

function cerd {
  if [[ -d "$1" ]]; then
    echo "Refusing to overwrite your $1 directory."
    exit 1
  fi
}

function entcd {
  echo 'Entering directory '"$1"
  cd "$1" || exit 1
}

function leacd {
  echo 'Leaving directory '"${PWD##*/}"
  cd ..
}

function cerfdl {
  local URL="$1"
  local FILENAME=${URL##*/}
  cerf "$FILENAME"
  # wget -O $FILENAME $URL || exit 1
  curl "$URL" > "$FILENAME" || exit 1
}

PROTOCOL='https'

if [[ -n "$1" ]]; then
  PROTOCOL="$1"
  shift
fi

case "$PROTOCOL" in
  https)
    BASE='://github.com/'
    ;;
  git)
    BASE='@github.com:'
    ;;
esac

if [[ ! -f 'Clockduino.ino' ]]; then
  echo "You must run this script from the sketch directory."
  exit 1
fi

cd ..

if [[ ! -d 'libraries' ]]; then
  echo "You must create a libraries directory for your Arduino sketch folder."
  exit 1
fi

echo 'Clockduino Library Fetcher'
echo 'v0.1'
echo 'admin@coding-squared.com'

# Fetch required libraries
entcd 'libraries'

echo "Fetching HTTP download libraries\n"

# Fetch OneWire library
echo "Fetching OneWire library"
cerfdl 'http://www.pjrc.com/teensy/arduino_libraries/OneWire.zip'
# Extract OneWire.zip
cerd 'OneWire'
unzip 'OneWire.zip'

echo "Fetching git libraries\n"

# Fetch the DallasTemperature library
echo "Fetching DallasTemperature library"
cerd 'DallasTemperature'
git clone $PROTOCOL$BASE'infomaniac50/Arduino-Temperature-Control-Library.git' 'DallasTemperature' || exit 1

# Use our branch
# cd 'DallasTemperature'
entcd 'DallasTemperature'
git co clockduino || exit 1
leacd

# Fetch the RTClib library
echo "Fetching RTClib library"
cerd 'RTClib'
git clone $PROTOCOL$BASE'infomaniac50/RTClib.git' || exit 1

# Use our branch
# cd 'RTClib'
entcd 'RTClib'
git co clock2412 || exit 1
leacd

# Fetch the LiquidTWI2 library
echo "Fetching LiquidTWI2 library"
cerd 'LiquidTWI2'
git clone $PROTOCOL$BASE'infomaniac50/LiquidTWI2.git' || exit 1

# Use our branch
# cd 'LiquidTWI2'
entcd 'LiquidTWI2'
git co clockduino || exit 1
leacd

# Fetch the SimpleTimer library
echo "Fetching SimpleTimer library"
cerd 'SimpleTimer'
git clone $PROTOCOL$BASE'infomaniac50/SimpleTimer.git' || exit 1
