#!/bin/bash

echo "Fetching libraries not available with git"

echo "Fetching OneWire library"
wget -O OneWire.zip http://www.pjrc.com/teensy/arduino_libraries/OneWire.zip

echo "Fetching DallasTemperature library"
wget -O DallasTemperature.zip http://download.milesburton.com/Arduino/MaximTemperature/DallasTemperature_LATEST.zip



echo ""
echo "Please unzip the two zip files in "`pwd`" to your arduino library folder."
